nosound : no
autostart : yes
speed : yes
test : yes
openbrowseriferror: no

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "WARNING"

  debug {
    receive = off
    autoreceive = off
    lifecycle = off
    fsm = off
    event-stream = off
    unhandled = off
  }
}



